#!/usr/bin/env bash
python pca.py sonar 10
python pca.py sonar 20
python pca.py sonar 30
python pca.py splice 10
python pca.py splice 20
python pca.py splice 30
python svd.py sonar 10
python svd.py sonar 20
python svd.py sonar 30
python svd.py splice 10
python svd.py splice 20
python svd.py splice 30
python isomap.py sonar 10
python isomap.py sonar 20
python isomap.py sonar 30
python isomap.py splice 10
python isomap.py splice 20
python isomap.py splice 30
